package models.depenses;

public enum Categorie {
    LOYER,
    VIE_QUOTIDIENNE,
    DONS,
    ASSURANCES,
    SANTE,
    ABONNEMENTS,
    REMBOURSEMENTS_EMPRUNTS,
    FRAIS_BANCAIRES,
    ESSENCE,
    TRANSPORTS,
    RESTAURANTS,
    BARS,
    AUTRES_SORTIES,
    MOBILIER,
    NUMERIQUE,
    VETEMENTS,
    ACHATS_DIVERS
}
